# Site settings
title: My Jekyll Site
description: A simple Jekyll site hosted on GitHub Pages
baseurl: "" # Leave this empty if deploying to the root of GitHub Pages
url: "https://victoriabiagi.github.io" # Replace <your-username> with your GitHub username

# Build settings
theme: minima # Default theme provided by Jekyll
plugins:
  - jekyll-feed # Optional plugin for RSS feed
  
# Markdown settings
markdown: kramdown
highlighter: rouge
