

# Site settings
title: My Jekyll Site
description: A simple Jekyll site hosted on GitHub Pages
baseurl: "" # Leave this empty if deploying to the root of GitHub Pages
url: "https://victoriabiagi.github.io" # Replace with your GitHub Pages URL

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed # Optional plugin for RSS feed
  - jekyll-remote-theme # Enables using a remote theme

# Markdown settings
markdown: kramdown
highlighter: rouge
